name: ci

on:
  push:
    branches: [master]
    tags:
      - "v1.*"
      - "v2.*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Tests
        run: |
          vendor/bin/phpunit

      - name: Publish
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
        run: |
          curl -X POST -H 'content-type:application/json' \
            "https://packagist.org/api/update-package?username=nicolasbrugneaux-passbase.com&apiToken=$PACKAGIST_API_TOKEN" \
            -d '{"repository":{"url":"https://github.com/passbase/passbase-php"}}'
